name: Run RSpec tests
on: [push]
jobs: 
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: 2.7
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec rspec
